[package]
name = "random-word-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dictionary2 = "1.0"
rand = "0.8"
